OID/OpenIDServer/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using OpenIDServer.Models;
using OpenIDServer.ViewModels;
using System.Security.Claims;
using static OpenIddict.Abstractions.OpenIddictConstants;

namespace OpenIDServer.Controllers
{
    public class AuthController : Controller
    {
        private readonly OpenIdDbContext _context;
        public AuthController(OpenIdDbContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Register(RegisterViewModel model)
        {
            if (ModelState.IsValid)
            {

                if (_context.Users.Any(u => u.Username == model.Username))
                {
                    ModelState.AddModelError("", "This username already exists");
                    return View(model);
                }

                var newUser = new User
                {
                    Username = model.Username,
                    Password = model.Password,
                    Email = model.Email
                };

                _context.Users.Add(newUser);
                await _context.SaveChangesAsync();

                return RedirectToAction("Login");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Login(string returnUrl)
        {
            TempData["returnUrl"] = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _context.Users
                    .FirstOrDefaultAsync(u => u.Username == model.Username && u.Password == model.Password);

                if (user != null)
                {
                    var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.Name, user.Username),
                        new Claim(ClaimTypes.Email, user.Email)
                    };

                    var identity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
                    var principal = new ClaimsPrincipal(identity);

                    await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principal);
                    var asdasd = Destinations.AccessToken;

                    return RedirectToAction("Index", "Home");
                }
                else
                {
                    ModelState.AddModelError("", "Invalid username or password");
                }
            }

            return View(model);
        }

        [HttpPost]
        public IActionResult GoogleLogin()
        {
            return Challenge(new AuthenticationProperties { RedirectUri = "/" }, "Google");
        }     
    }
}

OID/OpenIDServer/Controllers/AuthorizeController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore;
using System.Security.Claims;
using OpenIddict.Abstractions;
using OpenIddict.Server.AspNetCore;
using static OpenIddict.Abstractions.OpenIddictConstants;

namespace OpenIDServer.Controllers
{
    public class AuthorizeController : Controller
    {
        private readonly IOpenIddictApplicationManager _applicationManager;
        public AuthorizeController(IOpenIddictApplicationManager applicationManager)
        {
            _applicationManager = applicationManager;
        }

        [HttpGet("~/connect/authorize")]
        public IActionResult Authorize(string client_id, string response_type, string redirect_uri, string scope, string state)
        {
            TempData["ClientId"] = client_id;
            TempData["ResponseType"] = response_type;
            TempData["RedirectUri"] = redirect_uri;
            TempData["Scope"] = scope;
            TempData["State"] = state;

            if (User.Identity.IsAuthenticated)
            {

                return RedirectToAction("Index", "Home");
            }

            return RedirectToAction("Login", "Auth");
        }

        [HttpPost("~/connect/authorize")]
        public async Task<IActionResult> AuthorizePost(
            [FromForm] string client_id,
            [FromForm] string response_type,
            [FromForm] string redirect_uri,
            [FromForm] string scope,
            [FromForm] string state,
            [FromForm] string accept)
        {

            if (string.IsNullOrEmpty(client_id) || string.IsNullOrEmpty(redirect_uri) || string.IsNullOrEmpty(response_type))
            {
                return BadRequest("Required parameters are missing: client_id, redirect_uri or response_type");
            }

            TempData["ClientId"] = client_id;
            TempData["RedirectUri"] = redirect_uri;
            TempData["Scope"] = scope;
            TempData["State"] = state;

            var request = HttpContext.GetOpenIddictServerRequest()
                ?? throw new InvalidOperationException("OpenID Connect request could not be received");

            var result = await HttpContext.AuthenticateAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            if (!result.Succeeded)
            {
                return Challenge(
                    authenticationSchemes: CookieAuthenticationDefaults.AuthenticationScheme,
                    properties: new AuthenticationProperties
                    {
                        RedirectUri = $"{Request.PathBase}{Request.Path}{Request.QueryString}"
                    });
            }

            if (accept == "no")
            {
                return Forbid(authenticationSchemes: OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            }

            if (!User.Identity.IsAuthenticated)
            {
                return BadRequest(
                    new OpenIddictResponse
                    {
                        Error = Errors.AccessDenied,
                        ErrorDescription = "The resource owner or authorization server denied the request"
                    });
            }

            var application = await _applicationManager.FindByClientIdAsync(client_id) ?? throw new InvalidOperationException("This clientId was not found");

            var sub = result.Principal?.Identity?.Name ?? "open-id-api";

            var identity = new ClaimsIdentity(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);

            identity.AddClaim(new Claim(Claims.Subject, sub)
                     .SetDestinations(Destinations.AccessToken, Destinations.IdentityToken));

            identity.AddClaim(new Claim(Claims.Name, await _applicationManager.GetDisplayNameAsync(application)
                    ?? throw new InvalidOperationException("Application name not found"))
                    .SetDestinations(Destinations.AccessToken, Destinations.IdentityToken));

            identity.AddClaim(new Claim(Claims.Audience, "OpenID")
                .SetDestinations(Destinations.AccessToken));

            var claimsPrincipal = new ClaimsPrincipal(identity);
            claimsPrincipal.SetScopes(request.GetScopes());


            return SignIn(claimsPrincipal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
        }


        [HttpPost("~/connect/token")]
        public async Task<IActionResult> Exchange()
        {
            var request = HttpContext.GetOpenIddictServerRequest();


            if (request?.IsClientCredentialsGrantType() is not null)
            {
                var application = await _applicationManager.FindByClientIdAsync(request.ClientId);
                if (application is null)
                    throw new InvalidOperationException("This clientId was not found");

                var identity = new ClaimsIdentity(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);

                identity.AddClaim(new Claim(Claims.Subject, await _applicationManager.GetClientIdAsync(application)
                    ?? throw new InvalidOperationException("Client ID not found"))
                    .SetDestinations(Destinations.AccessToken, Destinations.IdentityToken));

                identity.AddClaim(new Claim(Claims.Name, await _applicationManager.GetDisplayNameAsync(application)
                    ?? throw new InvalidOperationException("Application name not found"))
                    .SetDestinations(Destinations.AccessToken, Destinations.IdentityToken));

                identity.AddClaim(new Claim(Claims.Audience, "OpenID")
                    .SetDestinations(Destinations.AccessToken));

                var scopes = request.GetScopes();
                identity.AddClaim(new Claim(Claims.Scope, string.Join(" ", scopes))
                    .SetDestinations(Destinations.AccessToken, Destinations.IdentityToken));

                var claimsPrincipal = new ClaimsPrincipal(identity);
                claimsPrincipal.SetScopes(request.GetScopes());

                return SignIn(claimsPrincipal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);
            }
            else if (request?.IsAuthorizationCodeGrantType() is not null)
            {
                var principal = (await HttpContext.AuthenticateAsync(OpenIddictServerAspNetCoreDefaults.AuthenticationScheme)).Principal;
                return SignIn(principal, OpenIddictServerAspNetCoreDefaults.AuthenticationScheme);

            }

            throw new NotImplementedException("The specified grant type is not implemented");
        }

        [HttpPost("~/connect/logout")]
        public IActionResult Logout(string redirect_uri)
        {
            HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            if (string.IsNullOrEmpty(redirect_uri))
            {
                redirect_uri = "/";
            }

            return Redirect(redirect_uri);
        }
    }
}

OID/OpenIDServer/Controllers/HomeController.cs
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using OpenIDServer.Models;
using OpenIDServer.ViewModels;

namespace OpenIDServer.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            if (User.Identity.IsAuthenticated)
            {
                ViewData["UserName"] = User.FindFirst(ClaimTypes.Name)?.Value;
                ViewData["UserEmail"] = User.FindFirst(ClaimTypes.Email)?.Value;
                ViewData["ClientId"] = TempData["ClientId"]?.ToString();
                ViewData["RedirectUri"] = TempData["RedirectUri"]?.ToString();
                ViewData["Scope"] = TempData["Scope"]?.ToString();
                ViewData["State"] = TempData["State"]?.ToString();
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

OID/OpenIDServer/Views/Home/Index.cshtml
@using Microsoft.AspNetCore.Authentication

@{
    var userName = ViewData["UserName"] as string;
    var userEmail = ViewData["UserEmail"] as string;
    var clientId = TempData["ClientId"] as string;
    var responseType = TempData["ResponseType"] as string;
    var responseType1 = TempData["ResponseType"] as string;
    var redirectUri = TempData["RedirectUri"] as string;
    var scope = TempData["Scope"] as string;
    var state = TempData["State"] as string;

    var authenticationResult = await Context.AuthenticateAsync();

    string issued = null;
    string expires = null;

    if (authenticationResult?.Properties?.Items != null)
    {
        issued = authenticationResult.Properties.Items[".issued"];
        expires = authenticationResult.Properties.Items[".expires"];
    }
}

<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
    <link rel="stylesheet" href="~/css/styles.css" />
</head>
<body>

    <div class="container">
        <h1>OpenID Demo</h1>

        @if (User.Identity.IsAuthenticated)
        {
            <div class="welcome-message">
                <h2>Welcome, @userName!</h2>
                <hr />
                <dl>
                    <dt>Email</dt>
                    <dd>@userEmail</dd>
                </dl>

                <dl>
                    <dt>Client ID</dt>
                    <dd>@clientId</dd>
                </dl>

                <dl>
                    <dt>Redirect URI</dt>
                    <dd>@redirectUri</dd>
                </dl>

                <dl>
                    <dt>Scope</dt>
                    <dd>@scope</dd>
                </dl>

                <dl>
                    <dt>State</dt>
                    <dd>@state</dd>
                </dl>

                <dl>
                    <dt>Issued</dt>
                    <dd>@issued</dd>
                </dl>

                <dl>
                    <dt>Expires</dt>
                    <dd>@expires</dd>
                </dl>

                <button class="btn btn-dark btn-outline-warning" type="button" onclick="showAuthorizeDialog()">Authorize</button>

                <script>
                    function showAuthorizeDialog() {
                        var result = confirm("Do you want to authorize this application?");
                        if (result) {
                            document.getElementById('authorizeForm').accept.value = "yes";
                            document.getElementById('authorizeForm').submit();
                        } else {
                            document.getElementById('authorizeForm').accept.value = "no";
                            document.getElementById('authorizeForm').submit();
                        }
                    }
                </script>

                <form id="authorizeForm" asp-controller="Authorize" asp-action="AuthorizePost" class="button-form" method="post">
                    <input type="hidden" name="client_id" value="@clientId" />
                    <input type="hidden" name="redirect_uri" value="@redirectUri" />
                    <input type="hidden" name="scope" value="@scope" />
                    <input type="hidden" name="state" value="@state" />
                    <input type="hidden" name="response_type" value="@responseType" />
                    <input type="hidden" name="accept" value="yes" />
                </form>



                <form asp-controller="Authorize" asp-action="Logout" class="button-form" method="post">
                    <button class="btn btn-dark btn-outline-danger" type="submit">Logout</button>
                </form>
            </div>
        }
        else
        {
            <div class="button-container">
                <form asp-controller="Auth" asp-action="Register" method="get">
                    <button class="btn btn-dark btn-outline-primary" type="submit">Register</button>
                </form>

                <form asp-controller="Auth" asp-action="Login" method="post">
                    <button class="btn btn-dark btn-outline-primary" type="submit">Login</button>
                </form>

                @*     <form asp-controller="Auth" asp-action="GoogleLogin" method="post">
                    <button class="btn btn-dark btn-outline-primary" type="submit">Login with Google</button>
                </form> *@

            </div>
        }
    </div>

</body>
</html>